Readme.md
demo.yml

docs: add terminalizer demo file and gif

---

src/cmd/config.go
src/cmd/preview.go
src/common/service.go
src/k8sutils/k8sutils.go

This is a backwards incompatible change for the configuration file and it part of the 1.0.0 version spec of the configuration file

feature: add ability to exclude a namespace(s)

---

src/cmd/config.go
src/cmd/import.go
src/common/service.go
src/config/config.go

feature: support tags that are updated and tags that are append only

---

src/common/service.go

protect against empty key value in tag create and assign

---

src/cmd/config.go
src/common/service.go
src/config/config.go
src/k8sutils/k8sutils.go

feature: support targeting ANY k8s resource in the cluster

---

src/cmd/config.go
src/cmd/preview.go
src/common/jqparser.go
src/common/service.go
src/k8sutils/k8sutils.go
test/vault-crd.yaml
test/vault.yaml

feature: add ability to exclude resources based on jq expressions that return truthy

---

src/common/jqparser.go
src/common/service.go
src/k8sutils/k8sutils.go

Improves the JQ parsing performance 100x

---

src/common/service.go

bugfix: bubble up k8s client errors

---

src/cmd/config.go
src/go.mod
src/go.sum

feature: add command `config schema` for generating the jsonschema for the configuration file

---

src/k8sutils/k8sutils.go

bugfix: Deprecated selector "labels" but used incorrect spelling of labels in the json tags

---

src/common/jqparser.go
src/common/service.go
src/jq/jq.go

bugfix: bubble up JQ errors are warning logs to help diagnose problems

---

src/cmd/preview.go
src/cmd/root.go

feature: add ability to restrict `service preview` to json output to pipe to jq for debugging

---

.github/workflows/release.yaml
.github/workflows/test.yml
src/go.mod

Updating the expected go version

update versions for go module and github action

---

Readme.md

Fix broken link to [kubectl docs](https://docs.opslevel.com/docs/kubernetes-integration)
N/A

update README link to opslevel documentation

---

.changes/unreleased/Docs-20240117-193749.yaml
CONTRIBUTING.md
Readme.md
docs/Local-Development.md
docs/example-opslevel-k8s.yaml
docs/example-pod.yaml

These are useful instructions that explain how to tophat changes locally. It also gives a decent overview of how the program works.
**REVIEWERS- click here to view the rendered docs:**
1. https://github.com/OpsLevel/kubectl-opslevel/blob/ta/contributing-md/docs/Local-Development.md
2. https://github.com/OpsLevel/kubectl-opslevel/blob/ta/contributing-md/CONTRIBUTING.md
3. https://github.com/OpsLevel/kubectl-opslevel/blob/ta/contributing-md/Readme.md

New CONTRIBUTING.md | Local dev/tophatting instructions

---

.github/workflows/release.yaml
.github/workflows/test.yml

add caching to CI

---

.github/workflows/test.yml
Taskfile.yml

use latest from submodules during test, via task ci

---

.changie.yaml
.github/workflows/changie-gen.yml
Taskfile.yml
src/common/reconciler.go
src/go.mod

https://github.com/OpsLevel/team-platform/issues/186
Preview:
<details>
```
~/r/kubectl-opslevel/src ta/nilaway ❯ go run main.go service preview 1                              Ruby 3.0.0 01:36:03 pm
1:36PM INF [/v1/pods] Informer is ready and synced
The following data was found in your Kubernetes cluster ...
[
{
"Name": "worker-etl-7478676db-7bpfk",
"Description": "null",
"Owner": "null",
"Aliases": [
"staging-worker-etl-7478676db-7bpfk"
],
"TagAssigns": [
{
"key": "k8s_created",
"value": "2024-01-30T18:29:24Z"
},
{
"key": "app.kubernetes.io/name",
"value": "worker"
},
{
"key": "app.kubernetes.io/part-of",
"value": "opslevel"
},
{
"key": "pod-template-hash",
"value": "7478676db"
},
{
"key": "app.kubernetes.io/component",
"value": "sidekiq"
},
{
"key": "app.kubernetes.io/instance", …
```

Add `nilaway` to increase safety in kubectl-opslevel

---

.github/workflows/release.yaml
src/.goreleaser.yml

[#216](https://github.com/OpsLevel/team-platform/issues/216)
Finishing tonight, just need to include updated path to released tar.gz

update version and url in homebrew Formula on release

---

.github/workflows/release.yaml

add repo dispatch trigger to release workflow

---

.github/workflows/release.yaml

fix version update for homebrew Forumula

---

.github/workflows/release.yaml

Related to [Formula PR](https://github.com/OpsLevel/homebrew-tap/pull/8)

add git commit to kubectl-opslevel release

---

.github/workflows/release.yaml

update release process to use brew bump-formula-pr

---

src/.goreleaser.yml

add brews block to goreleaser

---

Taskfile.yml
src/.golangci.yml

DevEx improvement
`task debug`
Optional args can be passed in following a `--`
`task debug -- version`

add debug task

---

src/cmd/config.go
src/cmd/reconcile.go

fix formatting

---

Taskfile.yml
src/common/client.go

use ServiceUpdateInputV2 when updating service
