common/service.go
This removes duplicates from the aliases list during `service preview` and `service import` so that we have cleaner output during preview and do not call the OpsLevel API duplicative times.
golang doesn't have native hashset support so the best way is to just run an array through a function that returns a list with the duplicates removed.
=> remove duplicates from aliases list

k8sutils/k8sutils.go
This should fix loading multiple files specified in KUBECONFIG (which get merged) - IE `/path/to/config/one:/path/to/config/two`
=> bugfix: load kubeconfig using client-go ConfigLoadingRules to support multi file KUBECONFIG settings

src/common/service.go
=> bugfix: remove overlapped keys that exist in parsed `tags.assign` if key name also exists in `tags.create`

Dockerfile
I noticed this is running jq 1.4. 
I'm not sure why what's under release is 1.4 but some of the filtering features are not available in that version and I can't make use of the new exclude feature unless I bump to 1.6.
So here it is.
=> feature: upgrade jq from 1.4 to 1.6

src/cmd/preview.go
=> feature: allow specifying a sample count on `service preview` to limit the amount of data returned

src/cmd/import.go, src/common/service.go
=> bugfix: skip over aliases that are empty strings as they are not valid to register

src/Dockerfile
Install `jq` from the OS repository, so that the integrity of the binary can be ensured with apt. This also bumps the version of `jq` to v1.6, it was previously pulling in v1.4.
=> Bump jq to v1.6

.changes/unreleased/Feature-20220717-114349.yaml, src/cmd/collect.go, src/cmd/config.go, src/cmd/reconcile.go, src/cmd/root.go, src/common/service.go, src/config/config.go
usage:
```sh
kubectl opslevel collect -i "https://app.opslevel.com/integrations/custom_event/eeb1f18e-7205-41a5-97fe-60a0657f062d" -f ./opslevel-k8s.yaml
```
This then spins up as a kubernetes controller watching for changes to k8s resources and submits them individually as payloads to the integration url.
By submitting them individually it will both reduce the load on our API server AND only submit payloads when changes to the k8s resources actually happen.
It is built ontop of the existing selectors in opslevel-k8s.yaml the idea being if you are using `kubectl opslevel reconcile` then you may also want to get those same things as payloads for custom event checks.
=> Add new command to send k8s resources as payloads to CEC

.changes/unreleased/Feature-20231220-200719.yaml, src/cmd/import.go, src/cmd/reconcile.go, src/cmd/root.go, src/common/client.go, src/common/parser.go, src/common/reconciler.go, src/common/reconciler_test.go
https://github.com/OpsLevel/kubectl-opslevel/issues/209
Unit tests pass.
=> Option to disable service creation when reconciling services

.github/workflows/changie-gen.yml, .github/workflows/dependabot-labels.yml
Identical changes to [this cli PR](https://github.com/OpsLevel/cli/pull/210). Also, [this PR](https://github.com/OpsLevel/cli/pull/227) showcases the auto-changie generating workflow
Use [reusable workflow from our actions repo](https://github.com/OpsLevel/actions/blob/main/.github/workflows/dependabot_pr_labels.yml) to trigger adding a changelog to Dependabot PRs with changie.
Note: the job in this workflow runs only if dependabot opens a PR.
=> use changie-action in changie-gen workflow

.changes/unreleased/Bugfix-20240105-163122.yaml, .changes/unreleased/Bugfix-20240105-163302.yaml, .changes/unreleased/Feature-20231220-154838.yaml, .gitignore, src/cmd/config.go, src/cmd/root.go, src/common/config.go, src/common/config_test.go
Continues the bugfixes in https://github.com/OpsLevel/kubectl-opslevel/pull/222
Before - had bug where we can't even generate the file if we don't have one. 
```
$ go run main.go service preview
panic: open ./opslevel-k8s.yaml: no such file or directory
$ go run main.go config sample
panic: open ./opslevel-k8s.yaml: no such file or directory
```
Now, we can get generate the file without getting stuck. I tested that `service preview` works. 
```
$ go run main.go config sample simple > $HOME/kuber.yaml
$ go run main.go service preview --config $HOME/kuber.yaml
$ go run main.go service preview # reads from ./opslevel-k8s.yaml
```
=> continue - upload config file with yaml, not viper

.changes/unreleased/Feature-20240116-105434.yaml, src/cmd/config.go
Extracted from https://github.com/OpsLevel/kubectl-opslevel/pull/235
This makes it much clearer to the user what went wrong with their config file.
Otherwise, the error message always relates to `version not expected version`.
=> Better error messages when reading config files

.changes/unreleased/Docs-20240117-193749.yaml, .changes/unreleased/Feature-20240117-143424.yaml, CONTRIBUTING.md, Readme.md, docs/Local-Development.md, docs/example-opslevel-k8s.yaml, docs/example-pod.yaml, src/cmd/import.go, src/cmd/preview.go, src/cmd/reconcile.go, src/cmd/signal.go, src/common/config.go, src/common/parser.go, src/common/signal.go
Backend change: https://github.com/OpsLevel/opslevel-k8s-controller/pull/20
https://github.com/OpsLevel/team-platform/issues/184
https://github.com/OpsLevel/team-platform/issues/183
<details>
Preview - notice that the program doesn't just crash but gracefully exits after processing 1 entry.
```
$ go run main.go service preview
2:24PM INF [/v1/pods] Informer is ready and synced
taking a massive 5 sec break for you to test out the interrupt
^C2:24PM INF Handling interruption signal=interrupt
The following data was found in your Kubernetes cluster ...
[
{
"Name": "random-nginx-1",
"Description": "i hope the stack works",
"Owner": "platform",
"Aliases": [
"default-random-nginx-1"
],
"TagAssigns": [
{
"key": "k8s_created",
"value": "2024-01-16T03:05:51Z"
},
{
"key": "hello",
"value": "world" …
```
=> Add support for SIGINT, SIGTERM with Context

.changes/unreleased/Bugfix-20240113-031926.yaml, .changes/unreleased/Bugfix-20240118-095350.yaml, .gitignore, src/common/reconciler.go, src/common/reconciler_test.go
https://github.com/OpsLevel/kubectl-opslevel/issues/210
https://github.com/OpsLevel/opslevel-jq-parser/pull/14 and https://github.com/OpsLevel/opslevel-jq-parser/pull/15
=> Fix tools not being deduplicated | Fix bug where tools logging causes nil pointer exception

src/.goreleaser.yml
I _think_ this will work... 🤔 
This changes the brew Formula that goreleaser generates:
- Add `go` as a dependency on `brew install opslevel/tap/kubectl`
- I'm fairly certain we're expecting folks using this to also have `jq` managed by brew
=> update brew formula from goreleaser to go build on brew install

Taskfile.yml
`task ci` had hardcoded paths to `jq`'s lib and include paths. This is a problem in CI and this update should help with that
`task ci` - still works 🎉
=> update task ci, finds jq include,lib paths

.changes/unreleased/Feature-20240131-093229.yaml, .github/workflows/release.yaml, src/.goreleaser.yml, src/Dockerfile, src/cmd/root.go, src/cmd/version.go, src/main.go
[Unify Version output across all tools and libraries](https://github.com/OpsLevel/team-platform/issues/213)
With the latest release, `kubectl opslevel version` does not output what we want.
Specify release version at `go build` time with `-X main.version=${VERSION} -X main.commit=${COMMIT}` flags.
Most of the changes in `src/cmd/version.go` are copies from our cli. `kubectl opslevel version`
Add `--short` to `version` command
```bash
cd <kubectl-opslevel-repo>/src
docker build --build-arg="VERSION=$(git describe)" --build-arg="COMMIT=$(git rev-parse --short HEAD)" -t test-version-cmd -f Dockerfile . 
docker run --rm test-version-cmd version
```
This outputs:
```json
{
"commit": "7a58cfe",
"version": "v2024.1.27",
"go": {
"version": "go1.21.6",
"compiler": "gc",
"os": "linux",
"arch": …
```
=> make version based on latest git tag and commit

Taskfile.yml, src/.golangci.yml
`task lint` was failing if a code from submodules are not found (pre-release code). We need to pull submodules before linting, but we also don't want CI to fail if linting some submodule code fails, so we don't lint that anymore
`task ci`
=> fix task ci, pulls submodules before linting, skip linting submodules

.github/workflows/release.yaml
[kubect-opslevel release ticket](https://github.com/OpsLevel/team-platform/issues/260)
Previous release published `tmp.rb` as a Formula too. This resolves that.
=> remove tmp file in release workflow

.changes/v2024.3.18.md
This PR updates the current release log for to be more accurate. 
In the future we might want to look up which specific release changed the way logs look or how service aliases are compared.
[Code diff of last release](https://github.com/OpsLevel/kubectl-opslevel/compare/v2024.3.4...v2024.3.18)
[Last release v2024.3.18](https://github.com/OpsLevel/kubectl-opslevel/releases/tag/v2024.3.18)
TODO post merge:
=> Add forgotten changelogs to latest release

src/common/reconciler.go
https://github.com/OpsLevel/team-platform/issues/380
The customer was seeing
```
unexpected happened: got service with alias 'totem-appdir' but the result has no ID
```
But if this is the only alias too lookup by and since there is no actual API error we default to creating the service.   It seems there might be an API race condition with service lookup.  So this detects that situation and defers the reconciliation untill next time where hopefully it won't have this problem.
=> Potential fix for customer reported potential race condition

.changes/unreleased/Feature-20240903-173336.yaml, .changes/unreleased/Feature-20240903-173435.yaml, src/cmd/import.go, src/cmd/reconcile.go, src/cmd/root.go, src/common/parser.go, src/common/reconciler.go, src/common/reconciler_test.go
Resolves #306
During service update names can change and in certain situation can cause unwanted alias generation to have `_2` put on the end.
Add a flag which disables updating the service name to prevent this in certain situations.  This default is likely better then before so it is the new default.
=> Add ability to disable service name updates

.changes/unreleased/Feature-20240904-151102.yaml, src/cmd/config.go
Resolves #
When you start up the tool `service import` or `service reconcile` it fails when no configuration file is found or passed in.
Fallback to the sample configuration to make getting started with the tool easy - also makes manual testing easier.
=> fix for sample testing

.changes/unreleased/Security-20240903-165711.yaml, src/Dockerfile
Resolves #
Our container was reported to have vulns in it and i was under the impression the container was just the go binary but it was not.
Change the image to be JUST the binary.
=> Update Dockerfile to fix vulns reported

src/common/configs/config_sample.yaml, src/common/configs/config_simple.yaml
Slack context: https://jk-labs.slack.com/archives/C01K732BV51/p1726162518585529
propose the aliases stanza be updated to be:
```
aliases:
- .metadata.name
- '"k8s:\(.metadata.name)-\(.metadata.namespace)"'
- '"\(.metadata.namespace)-\(.metadata.name)"'
```
This would bias our syncer to consolidate these services under one service record in OL, and the aliases with the namespace suffix is still preserved. (IMO, we want to bias towards “one record for the service running across multiple namespaces” and customers can change their mind if they want)
Resolves #
=> bias towards consolidating a service running in multiple namespaces into a single service in OL

.github/workflows/release-test.yml, .github/workflows/release.yaml, .github/workflows/test.yml
=> add missing cache-dependency-path in setup-go GH action
